server:
  port: ${SERVER_PORT:8083}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/agiledb_task}
    username: ${DB_USERNAME:task_service_role}
    password: ${DB_PASSWORD:secret}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: task_schema
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongodb:27017/agile_tasks}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mvc:
    problemdetails:
      enabled: true
