spring.application.name=user_service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/agiledb}
spring.datasource.username=${DB_USERNAME:user_service_role}
spring.datasource.password=${DB_PASSWORD:user_secret}
spring.jpa.properties.hibernate.default_schema=user_schema

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

app.jwt.secret=change-this-secret-to-32-chars-minimum
app.jwt.expiration-seconds=86400
spring.mvc.problemdetails.enabled=true
