apiVersion: v1
kind: Secret
metadata:
  name: agile-secret
  namespace: agile-app
type: Opaque
stringData:
  # RabbitMQ Credentials
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"

  # PostgreSQL Credentials
  POSTGRES_PASSWORD: "your_postgres_password"
  USER_DB_PASSWORD: "user_secret"
  PM_DB_PASSWORD: "pm_secret"
  TASK_DB_PASSWORD: "secret"

  # JWT Secrets (used for Token verification in Gateway and User service)
  JWT_SECRET: "this-is-a-very-long-secret-key-for-jwt-signing-and-verification-32-bytes"

  # Mail Credentials
  MAIL_USERNAME: "your_email@gmail.com"
  MAIL_PASSWORD: "your_16_character_app_password"
